channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.9.18
  - pip
  - pip:
      - azure-ai-ml==1.13.0
      - azureml-mlflow==1.55.0
      - pyarrow==15.0.0
      - scikit-learn==1.3.2
      - pandas==2.0.3
      - joblib==1.3.2
      - matplotlib==3.7.5
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-client
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-collector
